name: Update S3 Data

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "30 16 * * 5" # Runs at 10:30 PM IST every Friday

jobs:
  update-s3-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.3"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Update S3 data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: uv run download.py --sync-s3
